#!/usr/bin/env bash

test -z "$CXX" && CXX=g++

SRC=(
    00-1-initial
    00-2-fruitfav
    01-1-score
    01-2-sale
    02-1-sizeof
)

CFLAGS=(
    -ggdb
)

function compile_one() {
    set -eux
    "$CXX" -o "$(dirname "$0")"/"$1" "${CFLAGS[@]}" "$(dirname "$0")"/"$1".cpp
    exit 0
}

function clean_object() {
    set -eux
    cd "$(dirname "$0")" && rm -f "${SRC[@]}" ./*.o
    exit 0
}

function help_message() {
    printf "
./compile: Simple Compile Bash Script

help: show this message
all: compile all programs
clean: clean binary files
<program_name>: compile <program_name>.cpp

Note. You can use \`CXX=clang++ ./compile all\` to set your custom compiler to clang++

"
    exit 0
}

function compile_all() {
    set -eux
    for i in "${SRC[@]}"
    do
        "$CXX" -o "$(dirname "$0")"/"$i" "${CFLAGS[@]}" "$(dirname "$0")"/"$i".cpp
    done
    exit 0
}

test "$0" = "$(dirname "$0")/clean" && clean_object
test -z "$1"          && help_message
test "$1" = "all"     && compile_all
test "$1" = "clean"   && clean_object
test "$1" = "help"    && help_message
for i in "${SRC[@]}"
do
    test "$1" = "$i" && compile_one "$1"
done
help_message
