#!/usr/bin/env bash

test -z "$CXX" && CXX=g++

SRC=(
    00-initial
    00-2-fruitfav
)

function compile_one() {
    set -eux
    "$CXX" -o $1 $1.cpp
    exit 0
}

function clean_object() {
    set -eux
    rm -f ${SRC[@]} *.o
    exit 0
}

function help_message() {
    printf "
./compile: Simple Compile Bash Script

help: show this message
clean: clean binary files
<program_name>: compile <program_name>.cpp

"
    exit 0
}

test $1 = "help"  && help_message
test $1 = "--help"  && help_message
test $1 = "clean" && clean_object
test -z $1 || compile_one $1

#############################################

set -eux
for i in ${SRC[@]}
do 
    "$CXX" -o "$i" "$i".cpp
done
